// <auto-generated />
using System;
using BarcodeFinal.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarcodeFinal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250917185229_AddProductTemplateRelation")]
    partial class AddProductTemplateRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BarcodeFinal.Models.Product", b =>
                {
                    b.Property<Guid>("ProductReferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TemplateReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductReferenceId");

                    b.HasIndex("TemplateReferenceId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BarcodeFinal.Models.Template", b =>
                {
                    b.Property<Guid>("TemplateReferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TemplateReferenceId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("BarcodeFinal.Models.Product", b =>
                {
                    b.HasOne("BarcodeFinal.Models.Template", null)
                        .WithMany()
                        .HasForeignKey("TemplateReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
